project:
  type: website
  output-dir: ./_site

website:
  navbar: 
    logo: docs/tongzhou_logo.jpg
    left:
      - text: Burwood
        file: docs/locations/burwood.qmd
      - text: Eastwood
        file: docs/locations/eastwood.qmd
      - text: Chatswood
        file: docs/locations/chatswood.qmd
      - text: Rhodes
        file: docs/locations/rhodes.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



